// Code generated by github.com/Jumpaku/cyamli v1.1.7, DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
	"strings"
)

type Func[Input any] func(subcommand []string, input Input, inputErr error) (err error)

type CLI struct {
	Evaluate CLI_Evaluate

	Validate CLI_Validate

	Version CLI_Version

	FUNC Func[CLI_Input]
}
type CLI_Input struct {
	Opt_Help bool
}

func resolve_CLI_Input(input *CLI_Input, restArgs []string) error {
	*input = CLI_Input{

		Opt_Help: false,
	}

	var arguments []string
	for idx, arg := range restArgs {
		if arg == "--" {
			arguments = append(arguments, restArgs[idx+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "-") {
			arguments = append(arguments, arg)
			continue
		}
		optName, lit, cut := strings.Cut(arg, "=")
		consumeVariables(optName, lit, cut)

		switch optName {
		default:
			return fmt.Errorf("unknown option %q", optName)

		case "-help", "-h":
			if !cut {
				lit = "true"

			}
			if err := parseValue(&input.Opt_Help, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		}
	}

	return nil
}

type CLI_Evaluate struct {
	FUNC Func[CLI_Evaluate_Input]
}
type CLI_Evaluate_Input struct {
	Opt_Format string

	Opt_Help bool

	Opt_InputPath string

	Opt_OutputPath string
}

func resolve_CLI_Evaluate_Input(input *CLI_Evaluate_Input, restArgs []string) error {
	*input = CLI_Evaluate_Input{

		Opt_Format: "yaml",

		Opt_Help: false,

		Opt_InputPath: "",

		Opt_OutputPath: "",
	}

	var arguments []string
	for idx, arg := range restArgs {
		if arg == "--" {
			arguments = append(arguments, restArgs[idx+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "-") {
			arguments = append(arguments, arg)
			continue
		}
		optName, lit, cut := strings.Cut(arg, "=")
		consumeVariables(optName, lit, cut)

		switch optName {
		default:
			return fmt.Errorf("unknown option %q", optName)

		case "-format", "-f":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_Format, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-help", "-h":
			if !cut {
				lit = "true"

			}
			if err := parseValue(&input.Opt_Help, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-input-path", "-i":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_InputPath, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-output-path", "-o":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_OutputPath, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		}
	}

	return nil
}

type CLI_Validate struct {
	FUNC Func[CLI_Validate_Input]
}
type CLI_Validate_Input struct {
	Opt_Help bool

	Opt_InputPath string
}

func resolve_CLI_Validate_Input(input *CLI_Validate_Input, restArgs []string) error {
	*input = CLI_Validate_Input{

		Opt_Help: false,

		Opt_InputPath: "",
	}

	var arguments []string
	for idx, arg := range restArgs {
		if arg == "--" {
			arguments = append(arguments, restArgs[idx+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "-") {
			arguments = append(arguments, arg)
			continue
		}
		optName, lit, cut := strings.Cut(arg, "=")
		consumeVariables(optName, lit, cut)

		switch optName {
		default:
			return fmt.Errorf("unknown option %q", optName)

		case "-help", "-h":
			if !cut {
				lit = "true"

			}
			if err := parseValue(&input.Opt_Help, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-input-path", "-i":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_InputPath, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		}
	}

	return nil
}

type CLI_Version struct {
	FUNC Func[CLI_Version_Input]
}
type CLI_Version_Input struct {
}

func resolve_CLI_Version_Input(input *CLI_Version_Input, restArgs []string) error {
	*input = CLI_Version_Input{}

	var arguments []string
	for idx, arg := range restArgs {
		if arg == "--" {
			arguments = append(arguments, restArgs[idx+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "-") {
			arguments = append(arguments, arg)
			continue
		}
		optName, lit, cut := strings.Cut(arg, "=")
		consumeVariables(optName, lit, cut)

		switch optName {
		default:
			return fmt.Errorf("unknown option %q", optName)

		}
	}

	return nil
}

func NewCLI() CLI {
	return CLI{}
}

func Run(cli CLI, args []string) error {
	subcommandPath, restArgs := resolveSubcommand(args)
	switch strings.Join(subcommandPath, " ") {

	case "":
		funcMethod := cli.FUNC
		if funcMethod == nil {
			return fmt.Errorf("%q is unsupported: cli.FUNC not assigned", "")
		}
		var input CLI_Input
		err := resolve_CLI_Input(&input, restArgs)
		return funcMethod(subcommandPath, input, err)

	case "evaluate":
		funcMethod := cli.Evaluate.FUNC
		if funcMethod == nil {
			return fmt.Errorf("%q is unsupported: cli.Evaluate.FUNC not assigned", "evaluate")
		}
		var input CLI_Evaluate_Input
		err := resolve_CLI_Evaluate_Input(&input, restArgs)
		return funcMethod(subcommandPath, input, err)

	case "validate":
		funcMethod := cli.Validate.FUNC
		if funcMethod == nil {
			return fmt.Errorf("%q is unsupported: cli.Validate.FUNC not assigned", "validate")
		}
		var input CLI_Validate_Input
		err := resolve_CLI_Validate_Input(&input, restArgs)
		return funcMethod(subcommandPath, input, err)

	case "version":
		funcMethod := cli.Version.FUNC
		if funcMethod == nil {
			return fmt.Errorf("%q is unsupported: cli.Version.FUNC not assigned", "version")
		}
		var input CLI_Version_Input
		err := resolve_CLI_Version_Input(&input, restArgs)
		return funcMethod(subcommandPath, input, err)

	}
	return nil
}

func resolveSubcommand(args []string) (subcommandPath []string, restArgs []string) {
	if len(args) == 0 {
		panic("command line arguments are too few")
	}
	subcommandSet := map[string]bool{
		"":         true,
		"evaluate": true, "validate": true, "version": true,
	}

	for _, arg := range args[1:] {
		if arg == "--" {
			break
		}
		pathLiteral := strings.Join(append(append([]string{}, subcommandPath...), arg), " ")
		if !subcommandSet[pathLiteral] {
			break
		}
		subcommandPath = append(subcommandPath, arg)
	}

	return subcommandPath, args[1+len(subcommandPath):]
}

func parseValue(dstPtr any, strValue ...string) error {
	switch dstPtr := dstPtr.(type) {
	case *[]bool:
		val := make([]bool, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []bool: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]float64:
		val := make([]float64, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []float64: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]int64:
		val := make([]int64, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []int64: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]string:
		val := make([]string, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []string: %w", str, err)
			}
		}
		*dstPtr = val
	case *bool:
		val, err := strconv.ParseBool(strValue[0])
		if err != nil {
			return fmt.Errorf("fail to parse %q as bool: %w", strValue[0], err)
		}
		*dstPtr = val
	case *float64:
		val, err := strconv.ParseFloat(strValue[0], 64)
		if err != nil {
			return fmt.Errorf("fail to parse %q as float64: %w", strValue[0], err)
		}
		*dstPtr = val
	case *int64:
		val, err := strconv.ParseInt(strValue[0], 0, 64)
		if err != nil {
			return fmt.Errorf("fail to parse %q as int64: %w", strValue[0], err)
		}
		*dstPtr = val
	case *string:
		*dstPtr = strValue[0]
	}

	return nil
}

func consumeVariables(...any) {}

func GetDoc(subcommands []string) string {
	switch strings.Join(subcommands, " ") {
	default:
		panic(fmt.Sprintf(`invalid subcommands: %v`, subcommands))

	case "":
		return "exprml-cli (v0.0.2)\n\nexprml-cli\n\n    Description:\n        exprml command line interface\n\n    Syntax:\n        $ exprml-cli  [<option>]...\n\n    Options:\n        -help[=<boolean>], -h[=<boolean>]  (default=false):\n            Shows help message.\n\n    Subcommands:\n        evaluate:\n            Evaluates a YAML expression.\n\n        validate:\n            Validates a YAML file.\n\n        version:\n            Shows the version of the exprml-cli command.\n\n\n"

	case "evaluate":
		return "exprml-cli (v0.0.2)\n\nexprml-cli evaluate\n\n    Description:\n        Evaluates a YAML expression.\n\n    Syntax:\n        $ exprml-cli evaluate [<option>]...\n\n    Options:\n        -format=<string>, -f=<string>  (default=\"yaml\"):\n            Output format. One of `yaml` or `json`.\n\n        -help[=<boolean>], -h[=<boolean>]  (default=false):\n            Show help message.\n\n        -input-path=<string>, -i=<string>  (default=\"\"):\n            Input YAML file path. stdin is used if not provided.\n\n        -output-path=<string>, -o=<string>  (default=\"\"):\n            Output file path. stdout is used if not provided.\n\n\n"

	case "validate":
		return "exprml-cli (v0.0.2)\n\nexprml-cli validate\n\n    Description:\n        Validates a YAML file.\n\n    Syntax:\n        $ exprml-cli validate [<option>]...\n\n    Options:\n        -help[=<boolean>], -h[=<boolean>]  (default=false):\n            Show help message.\n\n        -input-path=<string>, -i=<string>  (default=\"\"):\n            Input YAML file path. stdin is used if not provided.\n\n\n"

	case "version":
		return "exprml-cli (v0.0.2)\n\nexprml-cli version\n\n    Description:\n        Shows the version of the exprml-cli command.\n\n    Syntax:\n        $ exprml-cli version\n\n\n"

	}
}
